# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIr-quRYC6iwXniXhONKEMJ8m5hN4LKd
"""

import pandas as pd

df= pd.read_csv("/content/names.csv")

df.head()
df.tail()